ALTER TABLE "executed_actions"
ADD COLUMN "status" TEXT NOT NULL DEFAULT 'SUCCEEDED',
ADD COLUMN "error" TEXT,
ADD COLUMN "attempts" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "executed_actions" ALTER COLUMN "result" DROP NOT NULL;